### PR TITLE
Adding ROS namespace as one of the command line parse option

### PR DESCRIPTION
**Pull request by liushuya7**

### CODE REVIEW

**Comment by liushuya7** [comment]
I just tired to pass ROS command line arguments using [Passing ROS arguments to nodes via the command-line](https://docs.ros.org/en/iron/How-To-Guides/Node-arguments.html) but it didn't seem to work.

```bash
$ ros2 run universal_robot universal_robot -i 192.168.2.2 --ros-args -r __ns:=/blah

Error: Unknown option: --ros-args
/home/josh/BIGSS_WS/ur_ws/install/universal_robot/lib/universal_robot/universal_robot:
 -i <value>, --ip-address <value> : IP address for the UR controller (required)
 -D, --dark-mode : replaces the default Qt palette with darker colors (optional)
 -p <value>, --ros-period <value> : period in seconds to read all tool positions (default 0.01, 10 ms, 100Hz).  There is no point to have a period higher than the UR component (optional)
 -P <value>, --tf-ros-period <value> : period in seconds to read all components and broadcast tf2 (default 0.02, 20 ms, 50Hz).  There is no point to have a period higher than the UR's period (optional)
 -m, --component-manager : JSON file to configure component manager (optional)
[ros2run]: Process exited with failure 255
```

According to the ROS2 documentation, the namespace, which must start with a forward slash `/`, is set to `/blah` in this case. When I remove the `/`, then it gives:

```bash
$ ros2 run universal_robot universal_robot -i 192.168.2.2 --ros-args -r __ns:=blah

[WARN] [1694794199.967917006] [rcl]: Namespace not remapped to a fully qualified name (found: blah)
[ERROR] [1694794199.967935279] [rcl]: Failed to parse global arguments
terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'
  what():  failed to initialize rcl: Couldn't parse remap rule: '-r __ns:=blah'. Error: Expected lexeme type 19, got 18 at index 6, at ./src/rcl/lexer_lookahead.c:244, at ./src/rcl/arguments.c:371
[ros2run]: Aborted
```

Somehow, we need to make the node handle `--ros-args`.

**Comment by liushuya7** [comment]
You are correct. We can use `--ros-args` to add namespace. I think I fixed it. I just added command-line options so that the `cmnCommandLineOptions` in the node won't complain about `--ros-args` or `-r`.

It works now:
```bash
 $ ros2 run universal_robot universal_robot -i 192.168.2.2 --ros-args -r __ns:=/blah
Options provided:
 - IP address for the UR controller [192.168.2.2]
 - Passing ROS arguments to node via command-line []
 - Following --ros-args: remapping ROS node or namespace [__ns:=/blah]

File: mtsUniversalRobotScriptRT.cpp Line: 310 -  need to add joint configuration with names, type and maybe limits?  Can we retrieve these via API?
-W Class mtsUniversalRobotScriptRT: ReadPolyscopeVersion: version = 1.8.14035
[INFO] [1694795828.132591454] [rclcpp]: 1694795828.031706s, #1: UR: socket connected, IP: 192.168.2.2
[INFO] [1694795828.132694710] [rclcpp]: 1694795828.031887s, #2: UR-DashboardServer: Connected: Universal Robots Dashboard Server
```
```bash
$ ros2 topic list
/blah/SetRobotFreeDriveMode
/blah/SetRobotRunningMode
/blah/SetToolFrame
/blah/error
/blah/measured_cf
/blah/measured_cp
/blah/measured_cv
/blah/measured_js
/blah/move_cp
/blah/move_cr
/blah/move_jp
/blah/servo_cv
/blah/servo_jv
/blah/setpoint_cp
/blah/setpoint_js
/blah/stats/events/period_statistics
/blah/stats/publishers_ur_control/period_statistics
/blah/stats/subscribers/period_statistics
/blah/stats/tf_ur_control/period_statistics
/blah/stats/ur_control/period_statistics
/blah/status
/blah/warning
/parameter_events
/rosout
/tf
```

**Comment by adeguet1** [comment]
I don't think you even need to add the `-r` option.  Ideally the args should be sent to rclcpp first and this will remove anything starting with `__`.  I've done this for the dVRK:
* Use `rclcpp::init_and_remove_ros_arguments`: https://github.com/jhu-dvrk/ros2_dvrk_robot/blob/049f550172226758f6cbfc933927c148c513fdf0/src/dvrk_console_json.cpp#L81
* Then parse the remaining arguments: https://github.com/jhu-dvrk/ros2_dvrk_robot/blob/049f550172226758f6cbfc933927c148c513fdf0/src/dvrk_console_json.cpp#L136

This way we can still use `-r` for another usage.  Note that the method `cmnCommandLineOptions::Parse(std::vector<std::string>, std::ostream)` is fairly new so you will need to latest devel branch for cisst.  The new method also prints an error message if needed.

I should probably update all our `main` for the SAW components ported to ROS 2 :smiley:

**Comment by liushuya7** [comment]
I removed `options.AddOptionOneValue("r", "remap", ...);` but I kept `options.AddOptionNoValue("ros-args", "ros-args", ...)` The code is like this:

```cpp
std::vector<std::string> non_ros_arguments = rclcpp::init_and_remove_ros_arguments(argc, argv);
auto rosNode = std::make_shared<rclcpp::Node>("universal_robot");

// parse options
cmnCommandLineOptions options;
...

options.AddOptionOneValue("i", "ip-address",
                          "IP address for the UR controller",
                          cmnCommandLineOptions::REQUIRED_OPTION, &ipAddress);
options.AddOptionNoValue("D", "dark-mode",
                         "replaces the default Qt palette with darker colors");
options.AddOptionOneValue("p", "ros-period",
                          "period in seconds to read all tool positions (default 0.01, 10 ms, 100Hz).  There is no point to have a period higher than the UR component",
                          cmnCommandLineOptions::OPTIONAL_OPTION, &rosPeriod);
options.AddOptionOneValue("P", "tf-ros-period",
                          "period in seconds to read all components and broadcast tf2 (default 0.02, 20 ms, 50Hz).  There is no point to have a period higher than the UR's period",
                          cmnCommandLineOptions::OPTIONAL_OPTION, &tfPeriod);
options.AddOptionNoValue("ros-args", "ros-args",
                          "Passing ROS arguments to node via command-line",
                          cmnCommandLineOptions::OPTIONAL_OPTION);
```
Then I got an error
```bash
$ ros2 run universal_robot universal_robot -i 192.168.2.2 --ros-args -r __ns:=/dummy
Error: Unknown option: -r
/home/josh/BIGSS_WS/ur_ws/install/universal_robot/lib/universal_robot/universal_robot:
 -i <value>, --ip-address <value> : IP address for the UR controller (required)
 -D, --dark-mode : replaces the default Qt palette with darker colors (optional)
 -p <value>, --ros-period <value> : period in seconds to read all tool positions (default 0.01, 10 ms, 100Hz).  There is no point to have a period higher than the UR component (optional)
 -P <value>, --tf-ros-period <value> : period in seconds to read all components and broadcast tf2 (default 0.02, 20 ms, 50Hz).  There is no point to have a period higher than the UR's period (optional)
 -ros-args, --ros-args : Passing ROS arguments to node via command-line (optional)
 -m, --component-manager : JSON file to configure component manager (optional)
[ros2run]: Process exited with failure 255
```

**Comment by liushuya7** [comment]
It worked. Thanks!

**Comment by liushuya7** [comment]
> I don't think you even need to add the `-r` option. Ideally the args should be sent to rclcpp first and this will remove anything starting with `__`. I've done this for the dVRK:
> 
> * Use `rclcpp::init_and_remove_ros_arguments`: https://github.com/jhu-dvrk/ros2_dvrk_robot/blob/049f550172226758f6cbfc933927c148c513fdf0/src/dvrk_console_json.cpp#L81
> * Then parse the remaining arguments: https://github.com/jhu-dvrk/ros2_dvrk_robot/blob/049f550172226758f6cbfc933927c148c513fdf0/src/dvrk_console_json.cpp#L136
> 
> This way we can still use `-r` for another usage. Note that the method `cmnCommandLineOptions::Parse(std::vector<std::string>, std::ostream)` is fairly new so you will need to latest devel branch for cisst. The new method also prints an error message if needed.
> 
> I should probably update all our `main` for the SAW components ported to ROS 2 😃

Hi @adeguet1 , when are you going to update this node to use `init_and_remove_ros_arguments()`? Thanks!

**Comment by adeguet1** [comment]
I pushed some code to the devel branch.   Can you test?   If that works, I’ll merge to main.

On Sep 26, 2023, at 16:01, Joshua Liu ***@***.***> wrote:



I don't think you even need to add the -r option. Ideally the args should be sent to rclcpp first and this will remove anything starting with __. I've done this for the dVRK:

  *   Use rclcpp::init_and_remove_ros_arguments: https://github.com/jhu-dvrk/ros2_dvrk_robot/blob/049f550172226758f6cbfc933927c148c513fdf0/src/dvrk_console_json.cpp#L81
  *   Then parse the remaining arguments: https://github.com/jhu-dvrk/ros2_dvrk_robot/blob/049f550172226758f6cbfc933927c148c513fdf0/src/dvrk_console_json.cpp#L136

This way we can still use -r for another usage. Note that the method cmnCommandLineOptions::Parse(std::vector<std::string>, std::ostream) is fairly new so you will need to latest devel branch for cisst. The new method also prints an error message if needed.

I should probably update all our main for the SAW components ported to ROS 2 😃

Hi @adeguet1<https://github.com/adeguet1> , when are you going to update this node to use init_and_remove_ros_arguments()? Thanks!

**Comment by liushuya7** [comment]
Just tested it - it works! Thanks!

**Pull request closed without merging**
